// Export generation utilities.
// ALL field names MUST match docs/data-maps/THEME_DATA_MAP.md (export naming table).
// Do not rename fields without updating the data map first.
// SECURITY: JSON.stringify handles escaping for JSON — do NOT add sanitization to toJson().
// SECURITY: fontFamily is sanitized via allowlist before MD and CSS interpolation.
// layoutType, variant, and colorMode are intentionally excluded from all export formats.
// They are UI-routing/metadata fields only. The toHaveLength(44) test enforces this.

import type { Theme, ExportFormat } from '../types/theme'

// fontFamily allowlist: only safe characters for CSS font-family and Markdown.
// Rejects injection chars like @, (, ), ;, {, }, etc.
// Use literal space [ ] instead of \s — \s matches \n which is an injection vector.
// Each comma-separated font name is stripped of its surrounding quotes before the check,
// so "Space Grotesk" → Space Grotesk (passes). The original value is returned if all
// tokens pass, preserving proper CSS quoting in the output.
const FONT_FAMILY_ALLOWLIST = /^[a-zA-Z0-9 ,\-_.']+$/

function safeFontFamily(value: string): string {
  const trimmed = value.trim().slice(0, 100)
  // Strip surrounding quotes from each font name before checking allowlist
  const unquoted = trimmed
    .split(',')
    .map(f => f.trim().replace(/^["']|["']$/g, ''))
    .join(', ')
  return FONT_FAMILY_ALLOWLIST.test(unquoted) ? trimmed : 'system-ui'
}

export function exportTheme(theme: Theme, format: ExportFormat): string {
  switch (format) {
    case 'markdown':
      return toMarkdown(theme)
    case 'json':
      return toJson(theme)
    case 'css':
      return toCss(theme)
    case 'tailwind':
      return toTailwind(theme)
    case 'tailwind-v4':
      return toTailwindV4(theme)
  }
}

export function getFileName(_theme: Theme, format: ExportFormat): string {
  switch (format) {
    case 'markdown':
      return 'design_rules.md'
    case 'json':
      return 'design_tokens.json'
    case 'css':
      return 'variables.css'
    case 'tailwind':
      return 'tailwind.config.js'
    case 'tailwind-v4':
      return 'theme.css'
  }
}

export function downloadTheme(theme: Theme, format: ExportFormat): void {
  const content = exportTheme(theme, format)
  const fileName = getFileName(theme, format)
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = fileName
  document.body.appendChild(anchor)
  anchor.click()
  document.body.removeChild(anchor)
  URL.revokeObjectURL(url)
}

function toMarkdown(theme: Theme): string {
  const fontFamily = safeFontFamily(theme.typography.fontFamily)
  return `# Design Rules: ${theme.name}

> Generated by [motif](https://github.com/Khalid-Moukhtar/dsm-ai)
> Variant: ${theme.variant} · Mode: ${theme.colorMode}

---

## AI Instructions

Apply these design tokens throughout your codebase. Reference the token name — never hardcode the values below.

- **CSS / HTML**: \`var(--color-primary)\`, \`var(--spacing-md)\`, etc. (replace underscores with hyphens)
- **React**: \`style={{ color: 'var(--color-primary)' }}\`
- **Tailwind**: see design_tokens.json → plug values into your tailwind.config.js
- **When the user asks to change something visual**: update the token, not every instance.

---

## Colors

> Brand identity and semantic states — apply to backgrounds, text, borders, and interactive elements.

| Token | Value |
|-------|-------|
| color_primary | \`${theme.colors.primary}\` |
| color_primary_foreground | \`${theme.colors.primaryForeground}\` |
| color_secondary | \`${theme.colors.secondary}\` |
| color_secondary_foreground | \`${theme.colors.secondaryForeground}\` |
| color_background | \`${theme.colors.background}\` |
| color_surface | \`${theme.colors.surface}\` |
| color_text | \`${theme.colors.text}\` |
| color_text_muted | \`${theme.colors.textMuted}\` |
| color_border | \`${theme.colors.border}\` |
| color_accent | \`${theme.colors.accent}\` |
| color_error | \`${theme.colors.error}\` |
| color_success | \`${theme.colors.success}\` |
| color_warning | \`${theme.colors.warning}\` |
| color_focus_ring | \`${theme.colors.focusRing}\` |
| color_info | \`${theme.colors.info}\` |

## Typography

> Font stack, size scale, weights, and spacing — governs all text rendering.

| Token | Value |
|-------|-------|
| font_family | \`${fontFamily}\` |
| font_size_base | \`${theme.typography.fontSizeBase}\` |
| font_size_sm | \`${theme.typography.fontSizeSm}\` |
| font_size_lg | \`${theme.typography.fontSizeLg}\` |
| font_size_xl | \`${theme.typography.fontSizeXl}\` |
| font_size_2xl | \`${theme.typography.fontSize2xl}\` |
| font_size_3xl | \`${theme.typography.fontSize3xl}\` |
| font_weight_normal | \`${theme.typography.fontWeightNormal}\` |
| font_weight_medium | \`${theme.typography.fontWeightMedium}\` |
| font_weight_bold | \`${theme.typography.fontWeightBold}\` |
| line_height_base | \`${theme.typography.lineHeightBase}\` |
| letter_spacing_base | \`${theme.typography.letterSpacingBase}\` |

## Spacing

> Consistent gap scale — use for padding, margin, and layout gaps.

| Token | Value |
|-------|-------|
| spacing_xs | \`${theme.spacing.xs}\` |
| spacing_sm | \`${theme.spacing.sm}\` |
| spacing_md | \`${theme.spacing.md}\` |
| spacing_lg | \`${theme.spacing.lg}\` |
| spacing_xl | \`${theme.spacing.xl}\` |
| spacing_xxl | \`${theme.spacing.xxl}\` |
| spacing_xxxl | \`${theme.spacing.xxxl}\` |

## Border Radius

> Corner rounding scale — use for cards, inputs, buttons, and modals.

| Token | Value |
|-------|-------|
| border_radius_none | \`${theme.borderRadius.none}\` |
| border_radius_sm | \`${theme.borderRadius.sm}\` |
| border_radius_md | \`${theme.borderRadius.md}\` |
| border_radius_lg | \`${theme.borderRadius.lg}\` |
| border_radius_xl | \`${theme.borderRadius.xl}\` |
| border_radius_full | \`${theme.borderRadius.full}\` |

## Shadows

> Elevation scale — sm for hover states, md for cards, lg for panels, xl for modals and overlays.

| Token | Value |
|-------|-------|
| shadow_sm | \`${theme.shadows.sm}\` |
| shadow_md | \`${theme.shadows.md}\` |
| shadow_lg | \`${theme.shadows.lg}\` |
| shadow_xl | \`${theme.shadows.xl}\` |
`
}

function toJson(theme: Theme): string {
  const tokens = {
    color_primary: theme.colors.primary,
    color_primary_foreground: theme.colors.primaryForeground,
    color_secondary: theme.colors.secondary,
    color_secondary_foreground: theme.colors.secondaryForeground,
    color_background: theme.colors.background,
    color_surface: theme.colors.surface,
    color_text: theme.colors.text,
    color_text_muted: theme.colors.textMuted,
    color_border: theme.colors.border,
    color_accent: theme.colors.accent,
    color_error: theme.colors.error,
    color_success: theme.colors.success,
    color_warning: theme.colors.warning,
    color_focus_ring: theme.colors.focusRing,
    color_info: theme.colors.info,
    font_family: theme.typography.fontFamily,
    font_size_base: theme.typography.fontSizeBase,
    font_size_sm: theme.typography.fontSizeSm,
    font_size_lg: theme.typography.fontSizeLg,
    font_size_xl: theme.typography.fontSizeXl,
    font_size_2xl: theme.typography.fontSize2xl,
    font_size_3xl: theme.typography.fontSize3xl,
    font_weight_normal: theme.typography.fontWeightNormal,
    font_weight_medium: theme.typography.fontWeightMedium,
    font_weight_bold: theme.typography.fontWeightBold,
    line_height_base: theme.typography.lineHeightBase,
    letter_spacing_base: theme.typography.letterSpacingBase,
    spacing_xs: theme.spacing.xs,
    spacing_sm: theme.spacing.sm,
    spacing_md: theme.spacing.md,
    spacing_lg: theme.spacing.lg,
    spacing_xl: theme.spacing.xl,
    spacing_xxl: theme.spacing.xxl,
    spacing_xxxl: theme.spacing.xxxl,
    border_radius_none: theme.borderRadius.none,
    border_radius_sm: theme.borderRadius.sm,
    border_radius_md: theme.borderRadius.md,
    border_radius_lg: theme.borderRadius.lg,
    border_radius_xl: theme.borderRadius.xl,
    border_radius_full: theme.borderRadius.full,
    shadow_sm: theme.shadows.sm,
    shadow_md: theme.shadows.md,
    shadow_lg: theme.shadows.lg,
    shadow_xl: theme.shadows.xl,
  }
  return JSON.stringify(tokens, null, 2)
}

function toCss(theme: Theme): string {
  return `:root {
  /* Colors */
  --color-primary: ${theme.colors.primary};
  --color-primary-foreground: ${theme.colors.primaryForeground};
  --color-secondary: ${theme.colors.secondary};
  --color-secondary-foreground: ${theme.colors.secondaryForeground};
  --color-background: ${theme.colors.background};
  --color-surface: ${theme.colors.surface};
  --color-text: ${theme.colors.text};
  --color-text-muted: ${theme.colors.textMuted};
  --color-border: ${theme.colors.border};
  --color-accent: ${theme.colors.accent};
  --color-error: ${theme.colors.error};
  --color-success: ${theme.colors.success};
  --color-warning: ${theme.colors.warning};
  --color-focus-ring: ${theme.colors.focusRing};
  --color-info: ${theme.colors.info};

  /* Typography */
  --font-family: ${safeFontFamily(theme.typography.fontFamily)};
  --font-size-base: ${theme.typography.fontSizeBase};
  --font-size-sm: ${theme.typography.fontSizeSm};
  --font-size-lg: ${theme.typography.fontSizeLg};
  --font-size-xl: ${theme.typography.fontSizeXl};
  --font-size-2xl: ${theme.typography.fontSize2xl};
  --font-size-3xl: ${theme.typography.fontSize3xl};
  --font-weight-normal: ${theme.typography.fontWeightNormal};
  --font-weight-medium: ${theme.typography.fontWeightMedium};
  --font-weight-bold: ${theme.typography.fontWeightBold};
  --line-height-base: ${theme.typography.lineHeightBase};
  --letter-spacing-base: ${theme.typography.letterSpacingBase};

  /* Spacing */
  --spacing-xs: ${theme.spacing.xs};
  --spacing-sm: ${theme.spacing.sm};
  --spacing-md: ${theme.spacing.md};
  --spacing-lg: ${theme.spacing.lg};
  --spacing-xl: ${theme.spacing.xl};
  --spacing-xxl: ${theme.spacing.xxl};
  --spacing-xxxl: ${theme.spacing.xxxl};

  /* Border Radius */
  --border-radius-none: ${theme.borderRadius.none};
  --border-radius-sm: ${theme.borderRadius.sm};
  --border-radius-md: ${theme.borderRadius.md};
  --border-radius-lg: ${theme.borderRadius.lg};
  --border-radius-xl: ${theme.borderRadius.xl};
  --border-radius-full: ${theme.borderRadius.full};

  /* Shadows */
  --shadow-sm: ${theme.shadows.sm};
  --shadow-md: ${theme.shadows.md};
  --shadow-lg: ${theme.shadows.lg};
  --shadow-xl: ${theme.shadows.xl};
}
`
}

// Targets Tailwind CSS v3 (module.exports format).
// fontFamily: split raw value and strip surrounding quotes from each token —
// do NOT use safeFontFamily() here, as its allowlist rejects double-quoted names
// ("Space Grotesk" etc.), causing silent fallback for legitimate Google Fonts.
// The values go into a JS array (not interpolated into CSS/HTML), so stripping
// surrounding quotes per token is the correct and safe approach.
function toTailwind(theme: Theme): string {
  const fontArr = theme.typography.fontFamily
    .split(',')
    .map(f => f.trim().replace(/^["']|["']$/g, ''))

  const colors = {
    primary:    theme.colors.primary,
    secondary:  theme.colors.secondary,
    background: theme.colors.background,
    surface:    theme.colors.surface,
    text:       theme.colors.text,
    muted:      theme.colors.textMuted,
    border:     theme.colors.border,
    accent:     theme.colors.accent,
    error:      theme.colors.error,
    success:    theme.colors.success,
    warning:    theme.colors.warning,
    'focus-ring': theme.colors.focusRing,
    info:       theme.colors.info,
  }

  const fontSize = {
    sm:    [theme.typography.fontSizeSm,   { lineHeight: String(theme.typography.lineHeightBase) }],
    base:  [theme.typography.fontSizeBase, { lineHeight: String(theme.typography.lineHeightBase) }],
    lg:    [theme.typography.fontSizeLg,   { lineHeight: String(theme.typography.lineHeightBase) }],
    xl:    [theme.typography.fontSizeXl,   { lineHeight: '1.3' }],
    '2xl': [theme.typography.fontSize2xl,  { lineHeight: '1.2' }],
    '3xl': [theme.typography.fontSize3xl,  { lineHeight: '1.1' }],
  }

  const fontWeight = {
    normal: String(theme.typography.fontWeightNormal),
    medium: String(theme.typography.fontWeightMedium),
    bold:   String(theme.typography.fontWeightBold),
  }

  const spacing = {
    xs:   theme.spacing.xs,
    sm:   theme.spacing.sm,
    md:   theme.spacing.md,
    lg:   theme.spacing.lg,
    xl:   theme.spacing.xl,
    xxl:  theme.spacing.xxl,
    xxxl: theme.spacing.xxxl,
  }

  const borderRadius = {
    none: theme.borderRadius.none,
    sm:   theme.borderRadius.sm,
    DEFAULT: theme.borderRadius.md,
    lg:   theme.borderRadius.lg,
    xl:   theme.borderRadius.xl,
    full: theme.borderRadius.full,
  }

  const boxShadow = {
    sm: theme.shadows.sm,
    DEFAULT: theme.shadows.md,
    lg: theme.shadows.lg,
    xl: theme.shadows.xl,
  }

  return `/** @type {import('tailwindcss').Config} */
// Generated by motif
// Targets Tailwind CSS v3 (module.exports format)
module.exports = {
  theme: {
    extend: {
      colors: ${JSON.stringify(colors, null, 6).replace(/^/gm, '      ').trimStart()},
      fontFamily: {
        sans: ${JSON.stringify(fontArr)},
      },
      fontSize: ${JSON.stringify(fontSize, null, 6).replace(/^/gm, '      ').trimStart()},
      fontWeight: ${JSON.stringify(fontWeight, null, 6).replace(/^/gm, '      ').trimStart()},
      spacing: ${JSON.stringify(spacing, null, 6).replace(/^/gm, '      ').trimStart()},
      borderRadius: ${JSON.stringify(borderRadius, null, 6).replace(/^/gm, '      ').trimStart()},
      boxShadow: ${JSON.stringify(boxShadow, null, 6).replace(/^/gm, '      ').trimStart()},
    },
  },
}
`
}

// Targets Tailwind CSS v4 (@theme block format, file: theme.css).
// safeFontFamily() is used here — values are interpolated into CSS context.
function toTailwindV4(theme: Theme): string {
  const fontFamily = safeFontFamily(theme.typography.fontFamily)
  return `@import "tailwindcss";

/* Generated by motif */
/* Targets Tailwind CSS v4 (@theme block format) */
@theme {
  /* Colors */
  --color-primary: ${theme.colors.primary};
  --color-primary-foreground: ${theme.colors.primaryForeground};
  --color-secondary: ${theme.colors.secondary};
  --color-secondary-foreground: ${theme.colors.secondaryForeground};
  --color-background: ${theme.colors.background};
  --color-surface: ${theme.colors.surface};
  --color-text: ${theme.colors.text};
  --color-text-muted: ${theme.colors.textMuted};
  --color-border: ${theme.colors.border};
  --color-accent: ${theme.colors.accent};
  --color-error: ${theme.colors.error};
  --color-success: ${theme.colors.success};
  --color-warning: ${theme.colors.warning};
  --color-focus-ring: ${theme.colors.focusRing};
  --color-info: ${theme.colors.info};

  /* Typography */
  --font-family-sans: ${fontFamily};
  --text-sm: ${theme.typography.fontSizeSm};
  --text-base: ${theme.typography.fontSizeBase};
  --text-lg: ${theme.typography.fontSizeLg};
  --text-xl: ${theme.typography.fontSizeXl};
  --text-2xl: ${theme.typography.fontSize2xl};
  --text-3xl: ${theme.typography.fontSize3xl};
  --font-weight-normal: ${theme.typography.fontWeightNormal};
  --font-weight-medium: ${theme.typography.fontWeightMedium};
  --font-weight-bold: ${theme.typography.fontWeightBold};
  --leading-base: ${theme.typography.lineHeightBase};
  --tracking-base: ${theme.typography.letterSpacingBase};

  /* Spacing */
  --spacing-xs: ${theme.spacing.xs};
  --spacing-sm: ${theme.spacing.sm};
  --spacing-md: ${theme.spacing.md};
  --spacing-lg: ${theme.spacing.lg};
  --spacing-xl: ${theme.spacing.xl};
  --spacing-xxl: ${theme.spacing.xxl};
  --spacing-xxxl: ${theme.spacing.xxxl};

  /* Border Radius */
  --radius-none: ${theme.borderRadius.none};
  --radius-sm: ${theme.borderRadius.sm};
  --radius-md: ${theme.borderRadius.md};
  --radius-lg: ${theme.borderRadius.lg};
  --radius-xl: ${theme.borderRadius.xl};
  --radius-full: ${theme.borderRadius.full};

  /* Shadows */
  --shadow-sm: ${theme.shadows.sm};
  --shadow-md: ${theme.shadows.md};
  --shadow-lg: ${theme.shadows.lg};
  --shadow-xl: ${theme.shadows.xl};
}
`
}
