// Export generation utilities.
// ALL field names MUST match docs/data-maps/THEME_DATA_MAP.md (export naming table).
// Do not rename fields without updating the data map first.
// SECURITY: JSON.stringify handles escaping for JSON — do NOT add sanitization to toJson().
// SECURITY: fontFamily is sanitized via allowlist before MD and CSS interpolation.
// layoutType, variant, and colorMode are intentionally excluded from all export formats.
// They are UI-routing/metadata fields only. The toHaveLength(38) test enforces this.

import type { Theme, ExportFormat } from '../types/theme'

// fontFamily allowlist: only safe characters for CSS font-family and Markdown.
// Rejects injection chars like @, (, ), ;, {, }, etc.
// Use literal space [ ] instead of \s — \s matches \n which is a injection vector
const FONT_FAMILY_ALLOWLIST = /^[a-zA-Z0-9 ,\-_.']+$/

function safeFontFamily(value: string): string {
  const trimmed = value.trim().slice(0, 100)
  return FONT_FAMILY_ALLOWLIST.test(trimmed) ? trimmed : 'system-ui'
}

export function exportTheme(theme: Theme, format: ExportFormat): string {
  switch (format) {
    case 'markdown':
      return toMarkdown(theme)
    case 'json':
      return toJson(theme)
    case 'css':
      return toCss(theme)
  }
}

export function getFileName(_theme: Theme, format: ExportFormat): string {
  switch (format) {
    case 'markdown':
      return 'design_rules.md'
    case 'json':
      return 'design_tokens.json'
    case 'css':
      return 'variables.css'
  }
}

export function downloadTheme(theme: Theme, format: ExportFormat): void {
  const content = exportTheme(theme, format)
  const fileName = getFileName(theme, format)
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = fileName
  document.body.appendChild(anchor)
  anchor.click()
  document.body.removeChild(anchor)
  URL.revokeObjectURL(url)
}

function toMarkdown(theme: Theme): string {
  const fontFamily = safeFontFamily(theme.typography.fontFamily)
  return `# Design Rules: ${theme.name}

> Generated by [DSM — Design System Maker](https://github.com/Khalid-Moukhtar/dsm-ai)
> Variant: ${theme.variant} · Mode: ${theme.colorMode}

---

## Colors

| Token | Value |
|-------|-------|
| color_primary | \`${theme.colors.primary}\` |
| color_primary_foreground | \`${theme.colors.primaryForeground}\` |
| color_secondary | \`${theme.colors.secondary}\` |
| color_secondary_foreground | \`${theme.colors.secondaryForeground}\` |
| color_background | \`${theme.colors.background}\` |
| color_surface | \`${theme.colors.surface}\` |
| color_text | \`${theme.colors.text}\` |
| color_text_muted | \`${theme.colors.textMuted}\` |
| color_border | \`${theme.colors.border}\` |
| color_accent | \`${theme.colors.accent}\` |
| color_error | \`${theme.colors.error}\` |
| color_success | \`${theme.colors.success}\` |
| color_warning | \`${theme.colors.warning}\` |

## Typography

| Token | Value |
|-------|-------|
| font_family | \`${fontFamily}\` |
| font_size_base | \`${theme.typography.fontSizeBase}\` |
| font_size_sm | \`${theme.typography.fontSizeSm}\` |
| font_size_lg | \`${theme.typography.fontSizeLg}\` |
| font_size_xl | \`${theme.typography.fontSizeXl}\` |
| font_size_2xl | \`${theme.typography.fontSize2xl}\` |
| font_size_3xl | \`${theme.typography.fontSize3xl}\` |
| font_weight_normal | \`${theme.typography.fontWeightNormal}\` |
| font_weight_medium | \`${theme.typography.fontWeightMedium}\` |
| font_weight_bold | \`${theme.typography.fontWeightBold}\` |
| line_height_base | \`${theme.typography.lineHeightBase}\` |
| letter_spacing_base | \`${theme.typography.letterSpacingBase}\` |

## Spacing

| Token | Value |
|-------|-------|
| spacing_xs | \`${theme.spacing.xs}\` |
| spacing_sm | \`${theme.spacing.sm}\` |
| spacing_md | \`${theme.spacing.md}\` |
| spacing_lg | \`${theme.spacing.lg}\` |
| spacing_xl | \`${theme.spacing.xl}\` |
| spacing_xxl | \`${theme.spacing.xxl}\` |
| spacing_xxxl | \`${theme.spacing.xxxl}\` |

## Border Radius

| Token | Value |
|-------|-------|
| border_radius_none | \`${theme.borderRadius.none}\` |
| border_radius_sm | \`${theme.borderRadius.sm}\` |
| border_radius_md | \`${theme.borderRadius.md}\` |
| border_radius_lg | \`${theme.borderRadius.lg}\` |
| border_radius_xl | \`${theme.borderRadius.xl}\` |
| border_radius_full | \`${theme.borderRadius.full}\` |
`
}

function toJson(theme: Theme): string {
  const tokens = {
    color_primary: theme.colors.primary,
    color_primary_foreground: theme.colors.primaryForeground,
    color_secondary: theme.colors.secondary,
    color_secondary_foreground: theme.colors.secondaryForeground,
    color_background: theme.colors.background,
    color_surface: theme.colors.surface,
    color_text: theme.colors.text,
    color_text_muted: theme.colors.textMuted,
    color_border: theme.colors.border,
    color_accent: theme.colors.accent,
    color_error: theme.colors.error,
    color_success: theme.colors.success,
    color_warning: theme.colors.warning,
    font_family: theme.typography.fontFamily,
    font_size_base: theme.typography.fontSizeBase,
    font_size_sm: theme.typography.fontSizeSm,
    font_size_lg: theme.typography.fontSizeLg,
    font_size_xl: theme.typography.fontSizeXl,
    font_size_2xl: theme.typography.fontSize2xl,
    font_size_3xl: theme.typography.fontSize3xl,
    font_weight_normal: theme.typography.fontWeightNormal,
    font_weight_medium: theme.typography.fontWeightMedium,
    font_weight_bold: theme.typography.fontWeightBold,
    line_height_base: theme.typography.lineHeightBase,
    letter_spacing_base: theme.typography.letterSpacingBase,
    spacing_xs: theme.spacing.xs,
    spacing_sm: theme.spacing.sm,
    spacing_md: theme.spacing.md,
    spacing_lg: theme.spacing.lg,
    spacing_xl: theme.spacing.xl,
    spacing_xxl: theme.spacing.xxl,
    spacing_xxxl: theme.spacing.xxxl,
    border_radius_none: theme.borderRadius.none,
    border_radius_sm: theme.borderRadius.sm,
    border_radius_md: theme.borderRadius.md,
    border_radius_lg: theme.borderRadius.lg,
    border_radius_xl: theme.borderRadius.xl,
    border_radius_full: theme.borderRadius.full,
  }
  return JSON.stringify(tokens, null, 2)
}

function toCss(theme: Theme): string {
  return `:root {
  /* Colors */
  --color-primary: ${theme.colors.primary};
  --color-primary-foreground: ${theme.colors.primaryForeground};
  --color-secondary: ${theme.colors.secondary};
  --color-secondary-foreground: ${theme.colors.secondaryForeground};
  --color-background: ${theme.colors.background};
  --color-surface: ${theme.colors.surface};
  --color-text: ${theme.colors.text};
  --color-text-muted: ${theme.colors.textMuted};
  --color-border: ${theme.colors.border};
  --color-accent: ${theme.colors.accent};
  --color-error: ${theme.colors.error};
  --color-success: ${theme.colors.success};
  --color-warning: ${theme.colors.warning};

  /* Typography */
  --font-family: ${safeFontFamily(theme.typography.fontFamily)};
  --font-size-base: ${theme.typography.fontSizeBase};
  --font-size-sm: ${theme.typography.fontSizeSm};
  --font-size-lg: ${theme.typography.fontSizeLg};
  --font-size-xl: ${theme.typography.fontSizeXl};
  --font-size-2xl: ${theme.typography.fontSize2xl};
  --font-size-3xl: ${theme.typography.fontSize3xl};
  --font-weight-normal: ${theme.typography.fontWeightNormal};
  --font-weight-medium: ${theme.typography.fontWeightMedium};
  --font-weight-bold: ${theme.typography.fontWeightBold};
  --line-height-base: ${theme.typography.lineHeightBase};
  --letter-spacing-base: ${theme.typography.letterSpacingBase};

  /* Spacing */
  --spacing-xs: ${theme.spacing.xs};
  --spacing-sm: ${theme.spacing.sm};
  --spacing-md: ${theme.spacing.md};
  --spacing-lg: ${theme.spacing.lg};
  --spacing-xl: ${theme.spacing.xl};
  --spacing-xxl: ${theme.spacing.xxl};
  --spacing-xxxl: ${theme.spacing.xxxl};

  /* Border Radius */
  --border-radius-none: ${theme.borderRadius.none};
  --border-radius-sm: ${theme.borderRadius.sm};
  --border-radius-md: ${theme.borderRadius.md};
  --border-radius-lg: ${theme.borderRadius.lg};
  --border-radius-xl: ${theme.borderRadius.xl};
  --border-radius-full: ${theme.borderRadius.full};
}
`
}
